"""Portable IQ, WAV and SigMF import/export helpers for SANKET-Lite."""
from __future__ import annotations

import hashlib
import io
import json
import zipfile
from datetime import datetime, timezone

import numpy as np
from scipy.io import wavfile


SIGMF_VERSION = "1.2.5"


def _as_cf32_interleaved(iq: np.ndarray) -> bytes:
    """Encode complex IQ as little-endian float32 I,Q,I,Q... samples."""
    iq = np.asarray(iq, dtype=np.complex64)
    interleaved = np.empty(iq.size * 2, dtype="<f4")
    interleaved[0::2] = iq.real
    interleaved[1::2] = iq.imag
    return interleaved.tobytes()


def iq_bytes(iq: np.ndarray) -> bytes:
    return _as_cf32_interleaved(iq)


def wav_bytes(iq: np.ndarray, fs: float) -> bytes:
    """Make a standard stereo PCM WAV: left=I, right=Q."""
    peak = max(float(np.max(np.abs(iq.real))), float(np.max(np.abs(iq.imag))), 1.0)
    stereo = np.column_stack((iq.real / peak, iq.imag / peak))
    pcm = np.clip(stereo * 32767, -32768, 32767).astype(np.int16)
    output = io.BytesIO()
    wavfile.write(output, int(fs), pcm)
    return output.getvalue()


def sigmf_metadata(fs: float, sample_count: int, ground_truth: dict | None = None,
                   source_name: str = "sanket_capture.sigmf-data") -> dict:
    """Create a small standards-aligned SigMF metadata document."""
    meta = {
        "global": {
            "core:version": SIGMF_VERSION,
            "core:datatype": "cf32_le",
            "core:sample_rate": float(fs),
            "core:description": "Synthetic baseband IQ generated by SANKET-Lite",
            "core:recorder": "SANKET-Lite",
            "core:sha512": None,
        },
        "captures": [{"core:sample_start": 0, "core:frequency": 0}],
        "annotations": [{"core:sample_start": 0, "core:sample_count": int(sample_count)}],
    }
    if ground_truth:
        meta["annotations"][0].update({
            "sanket:known_modulation": ground_truth.get("modulation"),
            "sanket:known_symbol_rate_hz": ground_truth.get("symbol_rate"),
            "sanket:known_freq_offset_hz": ground_truth.get("freq_offset"),
            "sanket:known_snr_db": ground_truth.get("snr_db"),
        })
    return meta


def sigmf_bundle(iq: np.ndarray, fs: float, ground_truth: dict | None = None) -> bytes:
    """Return a ZIP containing the matching .sigmf-data and .sigmf-meta pair."""
    data = _as_cf32_interleaved(iq)
    meta = sigmf_metadata(fs, len(iq), ground_truth)
    meta["global"]["core:sha512"] = hashlib.sha512(data).hexdigest()
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("sanket_capture.sigmf-data", data)
        archive.writestr("sanket_capture.sigmf-meta", json.dumps(meta, indent=2))
    return output.getvalue()


def _decode_cf32(raw: bytes) -> np.ndarray:
    values = np.frombuffer(raw, dtype="<f4")
    if len(values) < 2 or len(values) % 2:
        raise ValueError("Expected interleaved float32 I/Q samples (an even number of floats).")
    return (values[0::2] + 1j * values[1::2]).astype(np.complex64)


def read_wav(raw: bytes) -> tuple[np.ndarray, float, dict]:
    fs, samples = wavfile.read(io.BytesIO(raw))
    if samples.ndim != 2 or samples.shape[1] < 2:
        raise ValueError("WAV input must have stereo I/Q channels: left=I, right=Q.")
    original_dtype = samples.dtype
    samples = samples.astype(np.float32)
    if np.issubdtype(original_dtype, np.integer):
        samples /= np.iinfo(original_dtype).max
    iq = (samples[:, 0] + 1j * samples[:, 1]).astype(np.complex64)
    return iq, float(fs), {"format": "stereo WAV (I/Q)", "metadata": {}}


def read_raw_iq(raw: bytes, fs: float) -> tuple[np.ndarray, float, dict]:
    return _decode_cf32(raw), float(fs), {"format": "cf32_le raw IQ", "metadata": {}}


def read_sigmf(data_raw: bytes, meta_raw: bytes) -> tuple[np.ndarray, float, dict]:
    meta = json.loads(meta_raw.decode("utf-8"))
    global_meta = meta.get("global", {})
    if global_meta.get("core:datatype") != "cf32_le":
        raise ValueError("This demo currently supports SigMF core:datatype 'cf32_le' only.")
    fs = global_meta.get("core:sample_rate")
    if not fs:
        raise ValueError("SigMF metadata does not contain core:sample_rate.")
    actual_hash = global_meta.get("core:sha512")
    if actual_hash and actual_hash != hashlib.sha512(data_raw).hexdigest():
        raise ValueError("SigMF data integrity check failed: SHA-512 does not match metadata.")
    return _decode_cf32(data_raw), float(fs), {"format": "SigMF cf32_le", "metadata": meta}


def read_sigmf_zip(raw: bytes) -> tuple[np.ndarray, float, dict]:
    """Read the portable SigMF ZIP produced by :func:`sigmf_bundle`."""
    with zipfile.ZipFile(io.BytesIO(raw)) as archive:
        names = archive.namelist()
        data_name = next((n for n in names if n.endswith(".sigmf-data")), None)
        meta_name = next((n for n in names if n.endswith(".sigmf-meta")), None)
        if not data_name or not meta_name:
            raise ValueError("ZIP must include one .sigmf-data file and one .sigmf-meta file.")
        return read_sigmf(archive.read(data_name), archive.read(meta_name))


def analysis_sigmf_report(iq: np.ndarray, fs: float, estimate: dict, verification: dict,
                          source_label: str) -> bytes:
    """Export analysis as a SigMF .sigmf-meta evidence document."""
    meta = sigmf_metadata(fs, len(iq), source_name=source_label)
    meta["global"].update({
        "core:description": "SANKET-Lite RF parameter-extraction evidence report",
        "sanket:source": source_label,
        "sanket:analysis_time_utc": datetime.now(timezone.utc).isoformat(),
    })
    cls = estimate["classification"]
    meta["annotations"][0].update({
        "sanket:predicted_modulation": cls["predicted_modulation"],
        "sanket:classification_confidence": cls["confidence"],
        "sanket:center_freq_offset_hz": estimate["center_freq_offset_hz"],
        "sanket:occupied_bw_hz": estimate["occupied_bw_hz"],
        "sanket:snr_db_est": estimate["snr_db_est"],
        "sanket:symbol_rate_est_hz": estimate["symbol_rate_est_hz"],
        "sanket:reconstruction_fidelity_score": verification.get("fidelity_score"),
        "sanket:verification_verdict": verification.get("verdict", verification.get("note")),
        "sanket:classifier_features": cls["features"],
    })
    return json.dumps(meta, indent=2, default=str).encode("utf-8")


def text_report(estimate: dict, verification: dict, fs: float, source_label: str) -> bytes:
    cls = estimate["classification"]
    body = f"""SANKET-Lite Analysis Report
============================
Source: {source_label}
SigMF datatype: cf32_le
Sample rate: {fs:.0f} Hz

PARAMETER EXTRACTION
Modulation: {cls['predicted_modulation']}
Confidence: {cls['confidence'] * 100:.0f}%
Center frequency offset: {estimate['center_freq_offset_hz']:.1f} Hz
Occupied bandwidth: {estimate['occupied_bw_hz']:.1f} Hz
Estimated SNR: {estimate['snr_db_est']:.1f} dB
Estimated symbol rate: {estimate['symbol_rate_est_hz'] or 'not applicable'} Hz

ANALYSIS-BY-SYNTHESIS
Fidelity score: {verification.get('fidelity_score', 'not evaluated')}
Verdict: {verification.get('verdict', verification.get('note', 'not available'))}

This human-readable summary accompanies the SigMF-compatible .sigmf-meta evidence report.
"""
    return body.encode("utf-8")
